; |
; |	Конфигурация Ultimate Sentry Guns ver. 0.8-b
; |	Автор: Shadow_Collider
; |
; |	Разработано для свободного пользования, не подлежит продаже
; |
; |	Версия конфигурации
; |	usg_ver = 0.8-b
; |

[Setting] (Настройки)
	; Основание пушки и сама башня имеют общую прочность:
	; 1 = Вкл.
	; 0 = Выкл.
	SENTRY COMMON SOLID = 0
	; Пушка стреляет по пушкам противника прицельно:
	; 1 = Вкл.
	; 0 = Выкл.
	SENTRY AIM SENTRY = 1
	; Пушка продолжает стрелять, если цель сломалась:
	; 1 = Вкл.
	; 0 = Выкл.
	SENTRY SHOT BREAK = 0
	; Коэффициент урона для уровня
	SENTRY DAMAGE MULTI = 0.5
	; Стандартный урон по игрокам
	SENTRY DAMAGE USER = 10.0
	; Стандартный урон по пушкам
	SENTRY DAMAGE SENTRY = 24.0
	; Интервал стрельбы
	SENTRY SHOT TIME = 0.15
	; Авто наведение ракет:
	; 1 = Вкл.
	; 0 = Выкл.
	SENTRY ROCKET AI = 1
	; Количество парных ракет
	SENTRY ROCKET COUNT = 2
	; Жизненный цикл ракет
	SENTRY ROCKET LIFE = 5.0
	; Скорость ракет
	SENTRY ROCKET SPEED = 1000.0
	; Интервал ракет
	SENTRY ROCKET TIME = 3.0
	; Максимальный угол поворота ракет
	SENTRY ROCKET CLAMP = 12.5
	; Интервал ракет между собой
	SENTRY ROCKET TIME BETWEEN = 0.25
	; Время, через которое пушка уничтожится окончательно
	SENTRY REPAIR TIME = 10.0
	; Процент восстановления пушки
	SENTRY CRASH LEVEL = 100.0
	; Номинал восстановления
	SENTRY REPAIR VALUE = 15.0
	; Номинал стоимости ремонта $
	SENTRY COST DAMAGE = 1
	; Номинал стоимости ремонта $
	SENTRY COST REPAIR = 5
	; Умножение дамага пушке
	SENTRY MULTI DAMAGE = 1.5
	; Умножение дамага пушке
	SENTRY EXPLOSION DAMAGE = 99.0
	; Максимальный угол видимости пушки по вертикали
	SENTRY VERTICAL LIMIT = 60.0
	; Процент, после которого пушка не видит цель 0..255
	SENTRY INVISIBLE LIMIT = 25.0

[Health Stats] (Настройка здоровья)
	; Урон в хитбокс
	SENTRY HITBOX DAMAGE = 1.0, 1.25, 1.5, 0.25
	; Здоровье башни
	SENTRY HEALTH HEAD MULTI = 1.5
	; Здоровье основания
	SENTRY HEALTH BASE MULTI = 1.0
	; Здоровье пушек
	SENTRY HEALTH LEVEL = 3000.0, 4500.0, 6000.0, 7500.0, 9000.0
	; Хитбоксы башни
	SENTRY HITS HEAD = 1, 2, 3
	; Хитбоксы основания
	SENTRY HITS BASE = 0	

[Force Stats] (Настройка сил)
	SENTRY RADIUS NUCLEAR = 250.0
	SENTRY RADIUS FIRE = 250.0
	SENTRY RADIUS GAS = 250.0
	SENTRY RADIUS PLASMA = 100.0
	SENTRY RADIUS EXP = 300.0
	SENTRY EXP FORCE = 500.0

[Attack Module Stats] (Настройки урона модулей)
	; Время накладывания радиации
	NUCLEAR TIME = 2.5
	; Урон от взрыва ракеты с радиацией
	NUCLEAR DAMAGE EXPLOSION = 25.0
	; Интервальный урон от радиации
	NUCLEAR INTERVAL DAMAGE = 5.0
	; Интервал нанесения урона радиацией
	NUCLEAR INTERVAL TIME = 0.5
	; Время накладывания огня
	FIRE TIME = 2.5
	; Урон от взрыва ракеты с огнём
	FIRE DAMAGE EXPLOSION = 25.0
	; Интервальный урон от огня
	FIRE INTERVAL DAMAGE = 5.0
	; Интервал нанесения урона огнём
	FIRE INTERVAL TIME = 0.5
	; Время накладывания газа
	GAS TIME = 2.5
	; Урон от взрыва ракеты с газом
	GAS DAMAGE EXPLOSION = 25.0
	; Интервальный урон от газа
	GAS INTERVAL DAMAGE = 3.5
	; Интервал нанесения урона газом
	GAS INTERVAL TIME = 0.5
	; Урон от пулемёта
	SHOTGUN DAMAGE = 15.0
	; Урон от плазмы
	PLASMA DAMAGE = 90.0
	; Интервал стрельбы плазмой
	PLASMA INTERVAL SHOT = 0.5
	; Скорость плазмы
	PLASMA SPEED SHOT = 1000.0
	; Урон от лазера
	LASER DAMAGE = 5.0
	; Интервал стрельбы лазером
	LASER INTERVAL SHOT = 0.2
	; Урон от электричества
	ELECTRIC DAMAGE = 5.0
	; Интервал стрельбы электричеством
	ELECTRIC INTERVAL SHOT = 0.2
	; Дистанция до следующей цели
	ELECTRIC DIST SCAN = 300.0
	; Количество цепочек "паровозиков"
	ELECTRIC COUNT TRACE = 2
	; Интервал хука "паровозика"
	HOOK INTERVAL = 0.2
	; Процент снижения урона за щитом
	DAMAGE FROZE EXP = 50.0
	; Время жизни щита под уроном модуля (В счёт поглощения урона не идёт)
	SHIELD DURABILITY = 5.0

[Aura Stats] (Настройки аур)
	; Шанс варьируется в пределах...  (0..100)
	; Интервал активации дополнений
	SENTRY AURA TIME = 5.0
	; Дальность дополнения
	SENTRY AURA DIST = 250.0
	; Максимальный вампиризм
	VAMPIRISM MAX VALUE = 255.0
	; Шанс вампиризма
	VAMPIRISM CHANCE = 15
	; Максимальное похищение от вампиризма
	VAMPIRISM MAX CLAMP = 25.0
	; Шанс отражения урона
	MIRROR CHANCE = 20
	; Максимальное отражение урона
	MIRROR MAX CLAMP = 25.0
	; Шанс двойного урона
	CRITICAL CHANCE = 25
	; Шанс заморозить игрока
	FROZE CHANCE = 50
	; Время заморозки игрока
	FROZE DURABILITY = 5.0
	; Шанс получения патронов
	AMMO CHANCE = 15
	; Количество получаемых патронов
	AMMO COUNT ADD = 30
	; Процент видимости игрока
	VANISH AMOUNT = 15.0
	; Шанс тряски игрока
	SHAKE CHANCE = 30

[Bone Attribute] (Кости модели)
	; Руки сюда лучше не совать
	SENTRY BONE AIM = 11
	SENTRY BONE HEAD = 9
	SENTRY BONE MAIN = 14
	SENTRY BONE LEFT = 55
	SENTRY BONE RIGHT = 70
	SENTRY BONE ROCKET LEFT = 47
	SENTRY BONE ROCKET RIGHT = 48
	SENTRY BONE LASER LEFT = 55
	SENTRY BONE LASER RIGHT = 70

[Access Addition] (Права доступа дополнений)
	; Права доступа на модули
	SENTRY LEVEL MODULE = v, v, v, v, m, m, b
	; Права доступа на ауры
	SENTRY LEVEL AURA = v, b, v, m, v, m, v
	; Права доступа на сброс пушки
	SENTRY RESET = h
	; Права доступа на улучшение после себя
	SENTRY UPDATE SELF = m
	; Права доступа на вип скин
	SENTRY VIP SKIN = m

[Access Count] (Количество на группу)
	a = 3000
	b = 3000
	m = 1000
	v = 5
	z = 3

[Access Reward] (Награда за убийства)
	a = 1450
	b = 450
	m = 400
	v = 350
	z = 300

[Access Reward Broker] (Награда за убийства посреднику)
	b = 200
	m = 150
	v = 125
	z = 100

[Cost Items] (Стоимость уровней)
	COST LEVEL 1 = 1000
	COST LEVEL 2 = 2000
	COST LEVEL 3 = 3000
	
	COST MODULE = 12500, 12500, 10500, 6250, 15000, 9100, 9100
	COST AURA = 12500, 16000, 8500, 16000, 6500, 12500, 12500
	COST RESET = 5000

[Attribute Sprite Items] (Атрибуты спрайтов)
	; Значение -1 (рандом)
	COLOR SPRITE MODULE DAMAGE = 55 255 55, 255 55 55, 55 155 255, 255 155 55, 255 255 255, 255 25 25, -1 -1 -1
	COLOR SPRITE AURA = 255 0 0, 255 255 0, 155 255 0, 50 50 255, 0 255 255, 150 150 255, 55 55 55
	
	SIZE BEAM LASER = 12
	SIZE BEAM ELECTRIC = 12
	FLUCT BEAM LASER = 0
	FLUCT BEAM ELECTRIC = 25

[Model List] (Список моделей)
	MODEL SENTRY = models/cgfrom/sentry/sentry_claws.mdl
	MODEL ALERT = models/cgfrom/sentry/alert.mdl
	MODEL ICE = models/cgfrom/sentry/ice_block4.mdl
	MODEL ROCKET NUCLEAR = models/cgfrom/sentry/model_shell.mdl
	MODEL ROCKET FIRE = models/cgfrom/sentry/rocket.mdl
	MODEL ROCKET GAS = models/cgfrom/sentry/rocket.mdl
	MODEL PLASMA FIRE = sprites/cgfrom/gas_exp3.spr
	MODEL SHIELD BREAK = models/cgfrom/sentry/shield_break.mdl
	MODEL SENTRY BREAK 1 = models/cgfrom/sentry/usg_leg.mdl
	MODEL SENTRY BREAK 2 = models/cgfrom/sentry/usg_tower.mdl
	MODEL SENTRY BREAK 3 = models/computergibs.mdl

[Sprite List] (Список спрайтов)
	SPRITE DESTROY = sprites/cgfrom/fire_exp.spr
	SPRITE BLOOD = sprites/blood.spr
	SPRITE BLOODSPRAY = sprites/bloodspray.spr
	SPRITE AURA BEAM = sprites/shockwave.spr
	SPRITE ROCKET FOLLOW = sprites/zbeam5.spr
	SPRITE NUCLEAR SMALL = sprites/cgfrom/nuclear_blur2.spr
	SPRITE NUCLEAR BIG = sprites/cgfrom/nucler_exp.spr
	SPRITE FIRE SMALL = sprites/cgfrom/fire_blur3.spr
	SPRITE FIRE BIG = sprites/cgfrom/fire_exp.spr
	SPRITE GAS SMALL = sprites/cgfrom/gas_blur2.spr
	SPRITE GAS BIG = sprites/cgfrom/gas_exp2.spr
	SPRITE PLASMA SHOT = sprites/cgfrom/laserminigun_explode_3.spr
	SPRITE BEAM LASER = sprites/zbeam6.spr
	SPRITE BEAM ELECTRIC = sprites/zbeam6.spr
	SPRITE PLASMA EXP = sprites/cgfrom/gas_exp3.spr
	SPRITE LASER = sprites/cgfrom/laser_dir.spr
	SPRITE ELECTRIC = sprites/cgfrom/electro_dir.spr	

[Sound List] (Список звуков)
	SOUND BUILD = cgfrom/sentry/building.wav
	SOUND UPGRADE = cgfrom/sentry/upgrade.wav
	SOUND WAVE = cgfrom/sentry/wave3.wav
	SOUND REPAIR = cgfrom/sentry/repair6.wav
	SOUND BREAKING = cgfrom/sentry/breaking.wav
	SOUND ALERT = cgfrom/sentry/alert.wav
	SOUND SHOT = cgfrom/sentry/shot38.wav
	SOUND PLASMA SHOT = cgfrom/sentry/plasma_shot.wav
	SOUND PLASMA EXP = cgfrom/sentry/plasma_exp7.wav
	SOUND MISSILE ROCKET = cgfrom/sentry/missile_rocket4.wav
	SOUND ROCKET EXPLOSION = cgfrom/sentry/rocket_nuclear_exp8.wav
	SOUND ROCKET FLY = cgfrom/sentry/rocket_fly7.wav
	SOUND LASER = cgfrom/sentry/laser15.wav
	SOUND ELECTRIC = cgfrom/sentry/energy3.wav
	SOUND ICE USE = cgfrom/sentry/ice_use.wav
	SOUND ICE BREAK = cgfrom/sentry/ice_break.wav
